<h1 style="width:960px;margin: 0 auto">Admin Area</h1><div class="admin-menu-wrapper">

	<button class="admin-menu-container" onclick="location.href='user-management.php';">			<div class="admin-icon">			<i class="fas fa-users-cog"></i>		</div>
		User<br>Management
	</button>

	<button class="admin-menu-container" onclick="location.href='ward-list-management.php';">			<div class="admin-icon">			<i class="fas fa-hospital-alt"></i>		</div>
		Ward<br />Management
	</button>	<button class="admin-menu-container" onclick="location.href='drug-management.php';">			<div class="admin-icon">			<i class="fas fa-tablets"></i>		</div>		Drug<br>Management	</button>	<button class="admin-menu-container" onclick="location.href='stock-order-data.php';">			<div class="admin-icon">			<i class="fas fa-chart-bar"></i>		</div>		Stock<br>Order Data	</button>	<button class="admin-menu-container" onclick="location.href='cd-audit.php';">			<div class="admin-icon">			<i class="fas fa-search-plus"></i>		</div>		CD Stock<br>Order Audit	</button>	<button class="admin-menu-container" onclick="location.href='cd-drug-management.php';">			<div class="admin-icon">			<i class="fas fa-pills"></i>		</div>		CD Drug<br />Management	</button>	<button class="admin-menu-container" onclick="location.href='ward-cd-audit.php';">			<div class="admin-icon">			<i class="fas fa-search"></i>		</div>		Ward CD<br>Audit	</button>	<button class="admin-menu-container" onclick="location.href='delete-cd-requisition.php';">			<div class="admin-icon">			<i class="fas fa-folder-minus"></i>		</div>		Delete CD<br>Requisition	</button>	<button class="admin-menu-container" onclick="location.href='cd-deleted-audit.php';">			<div class="admin-icon">			<i class="fas fa-search-minus"></i>		</div>		Deleted CD<br>Requisition Audit	</button>
</div>